name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Runs when you push to the main branch
  workflow_dispatch:  # Manual trigger

jobs:
  # Frontend job
  frontend:
    name: Build & Deploy Frontend (React)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        run: |
          cd client
          npm install

      - name: Build frontend
        run: |
          cd client
          npm run build

      - name: Run frontend tests
        run: |
          cd client
          npm test

      # Trigger Frontend Deploy (use the deploy hook secret)
      - name: Trigger Frontend Deploy (e.g., Vercel)
        run: |
          curl -X POST ${{ secrets.FRONTEND_DEPLOY_HOOK }}


  # Backend job
  backend:
    name: Build & Deploy Backend (Express + Prisma)
    runs-on: ubuntu-latest
    needs: frontend  # Ensures frontend is done first

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install backend dependencies
        run: |
          cd server
          npm install

      - name: Generate Prisma client
        run: |
          cd server
          npx prisma generate

      - name: Run migrations (Production-safe)
        run: |
          cd server
          npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Run backend tests
        run: |
          cd server
          npm test

      # Optional: Deploy to Render
      - name: Trigger Render Deploy Hook
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
